### ISSUE TITLE
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

### ISSUE THREAD

**Issue by Kampfader** [jakubfrasunek/netflixWatcher#2]
can u fix this? It can't use Gmail

Attaching to netflix_watcher_app, netflix_watcher_selenium
netflix_watcher_app       | Traceback (most recent call last):
netflix_watcher_app       |   File "/app/main.py", line 94, in <module>
netflix_watcher_app       |     fetch_last_unseen_email()
netflix_watcher_app       |   File "/app/main.py", line 68, in fetch_last_unseen_email
netflix_watcher_app       |     mail.login(EMAIL_LOGIN, EMAIL_PASSWORD)
netflix_watcher_app       |   File "/usr/local/lib/python3.9/imaplib.py", line 612, in login
netflix_watcher_app       |     raise self.error(dat[-1])
netflix_watcher_app       | imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

**Comment by LakYtron** [comment]
Enable IMAP in Gmail
and generate and use app password instede regular pwd
